DROP TABLE `personnel`;

CREATE TABLE `personnel` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `id` mediumint,
  `name` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  `street_addr` varchar(255) default NULL,
  `city` varchar(255),
  `zip` varchar(10) default NULL,
  `username` varchar(255) default NULL,
  `password` TEXT default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (1,"Simon, Eden W.","ligula.consectetuer.rhoncus@velit.edu","726-4876 Suspendisse Road","Bear","835804","Rhodes","ligula. Aenean gravida nunc sed pede."),(2,"Livingston, Jasper M.","non.dapibus@faucibusidlibero.co.uk","7623 Nisi. St.","Sangli","10814","Cantu","nulla. Integer"),(3,"Suarez, Basil O.","Duis@tincidunttempusrisus.net","Ap #338-1500 Arcu. Rd.","Laces/Latsch","30616","Meyers","fringilla ornare"),(4,"Warner, Zachary X.","tortor.dictum.eu@Curabiturconsequatlectus.edu","779-2446 Sed Rd.","Bahraich","37494-492","Holden","pede. Cras vulputate velit"),(5,"Boyd, Thane J.","Nullam.lobortis@velitQuisque.net","302-5883 Proin Road","Morro Reatino","27581","Cantrell","Donec feugiat metus sit amet ante. Vivamus non");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (6,"Day, Galena Q.","Integer@Class.org","Ap #384-2680 Magna, Street","Delhi","55262-074","Harris","nunc. In at"),(7,"Bell, Cooper T.","nec.metus.facilisis@dapibusid.net","971-3301 Turpis St.","Fumal","7381","Lara","venenatis vel, faucibus id, libero. Donec"),(8,"Stephenson, Kirk G.","amet.risus.Donec@enimmitempor.co.uk","Ap #288-4944 Pellentesque Ave","Potenza","74791-778","Howard","fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula"),(9,"Pickett, Garrett O.","ornare.lectus.justo@NullainterdumCurabitur.org","Ap #552-9759 In Rd.","Innisfail","06404","Key","augue scelerisque mollis. Phasellus libero mauris,"),(10,"Matthews, Peter Q.","ligula@orciadipiscingnon.ca","4031 Mi Av.","Narbolia","1817","Carlson","commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit,");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (11,"Hamilton, Brennan I.","ultricies.adipiscing@Morbiquisurna.edu","P.O. Box 580, 3567 Nulla. Avenue","Korneuburg","99656-043","Mann","ante."),(12,"Harrison, Mikayla Q.","purus.mauris@apurusDuis.edu","P.O. Box 346, 1352 Vitae Road","Villers-la-Tour","B6T 9E5","Hill","dapibus"),(13,"Ratliff, Gisela R.","auctor.velit.eget@erosnec.com","P.O. Box 805, 9763 Id St.","Melilla","6043","Murray","lobortis tellus justo"),(14,"Molina, Erica A.","interdum@pellentesquemassa.edu","714-1161 Morbi St.","Duisburg","16290","Dorsey","dolor. Fusce feugiat."),(15,"Chang, Carson Z.","Mauris.vel.turpis@egestas.com","P.O. Box 464, 778 Nunc. Ave","Ribeirão das Neves","43568","Willis","felis. Nulla tempor augue");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (16,"Fernandez, September P.","tempor.lorem.eget@Phasellusin.co.uk","Ap #522-2761 Eget, Rd.","Toowoomba","2787","Cohen","quis, pede. Praesent eu"),(17,"Saunders, Fatima F.","et@Integersemelit.edu","1822 Egestas Street","Villa Agnedo","06657","Valencia","Cras vulputate velit eu sem."),(18,"Acosta, Tara C.","Mauris.ut@ornare.com","P.O. Box 730, 4515 Cursus Rd.","Davenport","2241","Thompson","Sed pharetra, felis eget varius ultrices,"),(19,"Lawrence, Valentine E.","blandit.enim.consequat@etrutrumeu.com","Ap #630-146 Ligula. Road","Gravelbourg","285115","Gonzales","ut quam vel sapien imperdiet"),(20,"Juarez, Althea G.","a.mi@arcuAliquamultrices.ca","P.O. Box 373, 3685 Tortor. Rd.","Sint-Gillis-Waas","21111","Powers","primis in faucibus orci luctus et");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (21,"Dunn, Courtney J.","convallis.in@ac.ca","P.O. Box 236, 6002 Neque. Rd.","Wandre","14722-993","Workman","augue ut lacus. Nulla tincidunt, neque vitae semper egestas,"),(22,"Wise, Russell A.","tempor.bibendum.Donec@tellusSuspendisse.net","629-8418 Donec Rd.","Venlo","907373","Potter","scelerisque dui. Suspendisse ac metus vitae"),(23,"Harrison, Lillian V.","ut.cursus.luctus@ascelerisquesed.co.uk","Ap #927-6864 Amet Ave","Penticton","73284","Ward","nibh sit"),(24,"Roman, Cadman M.","Duis.sit@consequatenim.co.uk","P.O. Box 305, 9306 Ipsum. Street","Montacuto","41007","Ball","eu tellus. Phasellus"),(25,"Hopkins, Elaine J.","metus@acarcuNunc.com","415-4714 Lobortis St.","Waiuku","50-227","Phillips","Maecenas mi felis, adipiscing fringilla,");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (26,"Mcclure, Marshall Q.","Proin.nisl@Maecenas.com","104-9466 Non St.","Rouyn-Noranda","97563","Jenkins","lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse"),(27,"Cotton, Tobias C.","Nunc@velit.net","P.O. Box 573, 2618 Est. Street","Dijon","39476","Ferrell","eget odio. Aliquam vulputate ullamcorper magna. Sed"),(28,"Perkins, Yolanda V.","dolor@egetdictum.co.uk","P.O. Box 600, 3763 Arcu Avenue","Newport","90462","Austin","Integer eu lacus. Quisque"),(29,"Heath, Anastasia V.","metus@necmalesuada.org","268-5347 Scelerisque, Rd.","Bairnsdale","509593","Castillo","malesuada fames ac"),(30,"David, Zenaida W.","nec@utmiDuis.com","426-4791 Eget, Rd.","Beawar","807637","Lane","Mauris magna. Duis dignissim tempor arcu.");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (31,"Robertson, Arthur J.","dolor.elit.pellentesque@etultrices.co.uk","947-3433 Eget, Rd.","Beausejour","7430","Parker","dolor quam, elementum"),(32,"Tyler, Rajah H.","gravida.Aliquam.tincidunt@gravida.co.uk","Ap #931-6674 At, Rd.","Porpetto","65398-844","Hicks","lorem, sit amet ultricies sem magna"),(33,"Ford, Herrod M.","vulputate.velit@eget.co.uk","Ap #379-1514 Scelerisque Rd.","Castri di Lecce","79301","Horton","dolor sit amet, consectetuer adipiscing elit. Aliquam"),(34,"Everett, Beck V.","arcu.Vivamus@Inornare.net","303-1203 Elit, Av.","Moerkerke","E14 5QL","Mcdonald","Aenean massa. Integer vitae nibh. Donec"),(35,"Blevins, Uta J.","risus.Nulla.eget@ettristique.org","961-3042 Fames Av.","Alkmaar","5709","Summers","fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (36,"Joyce, Hiroko V.","nisi.Mauris@necante.net","Ap #914-8244 Congue. Rd.","Dreieich","17890","Bush","volutpat."),(37,"Walsh, Kermit K.","vulputate@scelerisque.com","331 Ultrices Rd.","Leugnies","64926","Horn","vitae"),(38,"Castro, Owen U.","elit.pede.malesuada@elit.net","420-9656 Vitae Street","Wichita","351353","Macias","interdum enim non nisi. Aenean eget metus. In"),(39,"Mack, Portia L.","torquent.per.conubia@Morbineque.net","Ap #106-9143 Convallis St.","Suxy","38025","Leon","accumsan"),(40,"Morris, Kirby O.","mi.lacinia@accumsaninterdumlibero.org","Ap #676-3979 Erat Rd.","R�ves","72010","Goff","in magna. Phasellus dolor elit, pellentesque");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (41,"Simmons, Debra Q.","mauris@molestieorci.co.uk","Ap #816-6050 Vitae Street","Flint","6627","Matthews","In mi pede, nonummy ut, molestie in, tempus"),(42,"Fields, Lesley E.","Sed.dictum@utpellentesqueeget.net","630-1644 Nunc Avenue","Rosi�res","40690","Dunlap","egestas a,"),(43,"Massey, Karly O.","non.enim@ac.ca","853-5842 Libero Rd.","Abolens","07-045","Coleman","eu nibh vulputate mauris sagittis placerat. Cras dictum"),(44,"Black, Casey F.","dui.nec.tempus@lobortistellus.ca","616-6023 Elit, Av.","Pfungstadt","82-402","Holcomb","Phasellus elit"),(45,"Mcknight, Claudia E.","Aenean.euismod@tellusjusto.edu","842-4171 Felis St.","Barrhead","17075","Becker","dui quis");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (46,"Farrell, Margaret R.","sollicitudin.commodo@ametdapibus.com","805-2285 Massa. St.","Bourges","27122-432","Gill","metus. In nec orci. Donec nibh."),(47,"Hart, Stephanie A.","pellentesque.eget.dictum@molestiearcu.edu","8744 Odio. St.","Tracadie-Shelia","37-544","Bond","Nulla interdum."),(48,"Saunders, Oprah Q.","Proin@ante.net","P.O. Box 113, 9433 Libero Road","Wetzlar","R6Y 1A1","Osborn","enim. Nunc"),(49,"Carney, Tiger E.","Proin.eget.odio@Curae.co.uk","Ap #131-9807 Ut St.","Nijmegen","91-605","Malone","Aliquam rutrum lorem ac risus. Morbi metus. Vivamus"),(50,"Ramirez, Kiara S.","commodo.at.libero@euturpis.com","P.O. Box 266, 449 Feugiat Road","Rocca San Felice","5634","Dominguez","sed, facilisis vitae,");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (51,"Baker, Claudia T.","ipsum.primis@nibhdolornonummy.ca","P.O. Box 768, 675 Lorem Street","Port Pirie","2279KB","Banks","conubia nostra, per inceptos"),(52,"Bartlett, Kane I.","natoque@facilisiseget.co.uk","2857 Donec Rd.","Coaldale","17434","Palmer","blandit at, nisi. Cum"),(53,"Tandon, Meghan B.","tandonmeghan@gmail.com","8475 Nec St.","Tielrode","8210YN","sassycassi128","4R3aLLyS3cur31TP4$$w0rd"),(54,"Ochoa, Wesley T.","egestas.urna@Donectempuslorem.ca","473-6562 Erat. Ave","Suarlee","7966","Stanton","eget odio. Aliquam vulputate ullamcorper magna. Sed eu"),(55,"Glover, Melanie C.","hendrerit.consectetuer@sitamet.net","4386 Dui Av.","Cariboo Regional District","219940","Silva","non sapien molestie orci tincidunt adipiscing. Mauris molestie");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (56,"Golden, Odette D.","nonummy.Fusce.fermentum@interdum.edu","P.O. Box 420, 3989 Mus. St.","Croydon","08-390","Fitzpatrick","magna. Duis"),(57,"Madden, Gail G.","eget.dictum.placerat@cursusdiamat.com","666-3427 Odio St.","LaSalle","14351-882","Weber","bibendum ullamcorper."),(58,"Schwartz, Jessica S.","varius.ultrices.mauris@feugiatnec.ca","Ap #745-7774 Aliquet St.","Khammam","94367","Hayes","arcu. Nunc"),(59,"Wyatt, Isadora N.","sociis@mauriselit.ca","5147 Placerat, Road","Meerut","DU2 1ZK","Alvarado","ipsum leo elementum sem, vitae aliquam eros"),(60,"Mccarthy, Ivana Z.","eget@noncursusnon.net","P.O. Box 719, 2090 Ligula. Rd.","Alacant","440205","Maxwell","aliquam, enim nec tempus scelerisque, lorem ipsum");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (61,"Christian, Chase E.","venenatis.a.magna@lectuspedeet.org","P.O. Box 881, 3805 Ligula Rd.","Vlezenbeek","2713","Oneil","ut, nulla. Cras eu tellus eu"),(62,"Calhoun, Dacey M.","consequat@convallisdolor.edu","P.O. Box 521, 3713 Enim, Avenue","Wolfville","39370","Horne","pharetra. Nam ac nulla. In"),(63,"Allen, Elton Z.","mollis@Inmi.edu","544-7977 Vitae Avenue","Andalo","GK1N 9KH","Mcdaniel","rhoncus. Donec est. Nunc"),(64,"Franklin, Bethany F.","eleifend.vitae@Mauris.edu","821-4365 Dui, St.","Dallas","S8 9YP","Kirk","dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu"),(65,"Ross, Tashya E.","tempor.erat.neque@gravida.net","Ap #570-9349 Nec St.","H�l�cine","6960","Foley","enim mi");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (66,"Juarez, Graham N.","erat@arcuAliquamultrices.com","2871 Mus. Avenue","Tywyn","4640CD","Wilcox","ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc"),(67,"Irwin, Imelda O.","molestie@nec.ca","1883 Maecenas Avenue","Dubuisson","997147","Carroll","amet nulla."),(68,"Barker, Beverly R.","libero@Fuscedolorquam.co.uk","667-6858 Aliquam Av.","Cajazeiras","2380","Dickerson","aliquet magna a"),(69,"Brock, Charissa Q.","malesuada.ut.sem@sed.net","7769 Luctus St.","Casciana Terme","5779","Weber","tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at"),(70,"Wise, Hilel T.","ligula.consectetuer@fermentumfermentum.edu","603-779 Risus Avenue","Nanton","2657","Thornton","justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (71,"Hooper, Ila G.","adipiscing.lobortis@augue.edu","379-3413 Purus, Avenue","Colchester","3741","Irwin","sem"),(72,"Hoover, Herrod G.","Proin@felisDonectempor.com","P.O. Box 407, 8848 Dui. Rd.","Châtellerault","83305","Mitchell","nibh dolor, nonummy ac, feugiat non,"),(73,"Lopez, Deacon U.","sodales.at@sitametconsectetuer.edu","P.O. Box 556, 312 Arcu St.","Neuss","41716","Bridges","consequat purus. Maecenas libero est, congue a,"),(74,"Ingram, Illana H.","facilisis@magnisdisparturient.net","P.O. Box 967, 8868 Proin Road","Oud-Turnhout","36536","Brewer","laoreet ipsum. Curabitur consequat, lectus"),(75,"Meyer, Amaya Q.","imperdiet.ullamcorper@sociis.edu","5912 Orci St.","Rae-Edzo","84163-457","Washington","arcu. Curabitur ut odio vel est tempor bibendum. Donec felis");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (76,"Oliver, Charity O.","magna@turpisIn.edu","9704 Eleifend. Street","Westkerke","7186","Bates","Vestibulum ut eros non enim commodo hendrerit. Donec porttitor"),(77,"Foster, Kristen Y.","facilisis@vulputate.com","756-6008 Augue St.","Melazzo","05141","Delgado","gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit"),(78,"Stout, Lysandra A.","euismod.mauris.eu@augueporttitor.co.uk","355-7750 Nullam Ave","Mount Isa","3703","Jacobson","hendrerit"),(79,"Rowland, Xena J.","per.conubia.nostra@vitae.co.uk","P.O. Box 639, 5836 Ligula Av.","Jemappes","9429","Mcgee","auctor, velit eget laoreet posuere, enim nisl"),(80,"Buckley, Arden L.","velit.Pellentesque@risusDuis.ca","3997 Sociis Avenue","Ludwigsburg","3270","Cervantes","enim nisl elementum");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (81,"Larson, Michael B.","luctus.sit.amet@tellusSuspendissesed.net","Ap #561-8766 Ligula. Rd.","Heppignies","L2L 1N9","Campbell","Curabitur consequat, lectus sit amet luctus vulputate,"),(82,"Ortiz, Tanek V.","aliquet.vel.vulputate@erat.edu","P.O. Box 425, 1618 Pulvinar Rd.","Certaldo","68149","Strong","dictum placerat, augue. Sed"),(83,"Daugherty, Ima J.","nunc.sit@diamvel.com","122-4692 Dui Ave","Beaufays","Z3 1LK","Meyers","Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit."),(84,"Chen, Driscoll M.","odio.Etiam@amet.net","P.O. Box 119, 7517 Neque Av.","Prato Carnico","1018","Blake","luctus et ultrices"),(85,"Cohen, Kitra O.","Aenean.eget@tempor.co.uk","P.O. Box 688, 9714 Malesuada Street","Thorn","1981","Lang","eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (86,"Bean, Germaine Q.","Aliquam@euelit.org","8720 Elit St.","Town of Yarmouth","2909","Key","eu tempor"),(87,"Waters, Dai G.","ligula.consectetuer@malesuada.co.uk","502-1039 Elit. Rd.","Sperlinga","49847","Humphrey","ornare"),(88,"Valenzuela, Kelly A.","justo@ullamcorpervelit.org","Ap #918-6811 Augue. St.","Villafranca in Lunigiana","20511","Hudson","vestibulum massa rutrum magna. Cras convallis"),(89,"Bray, Eaton Y.","magna.Cras.convallis@felis.ca","P.O. Box 339, 6351 Etiam Av.","Gebze","00767","Farmer","adipiscing non,"),(90,"Casey, Felicia T.","ipsum@lobortisultrices.org","529 A Rd.","Laakdal","7971","Bartlett","metus sit amet");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (91,"Griffith, Lucian O.","ultrices@Cras.com","3857 Dui Rd.","Rochester","I4P 5XS","Tate","sem"),(92,"Casey, Yoko L.","molestie@dolortempusnon.org","Ap #776-3185 Ridiculus St.","Jasper","34497","Ward","aliquet molestie"),(93,"Wilcox, Wayne I.","Mauris@Utsemperpretium.net","Ap #533-4054 A Av.","VTM","S7B 5M7","Sosa","commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus"),(94,"Bradshaw, Ora C.","Pellentesque@nonummyipsum.org","P.O. Box 547, 1614 Lobortis. Av.","Newport","6026","Pena","lectus"),(95,"Bruce, Jaden P.","Nulla.eu@massaVestibulumaccumsan.edu","P.O. Box 406, 4064 Interdum. Street","İmamoğlu","51995","Gallegos","iaculis nec, eleifend non, dapibus");
INSERT INTO `personnel` (`id`,`name`,`email`,`street_addr`,`city`,`zip`,`username`,`password`) VALUES (96,"Chen, Felix V.","enim@vulputate.edu","P.O. Box 793, 1877 Placerat. Rd.","Falkensee","337258","Morse","nibh enim, gravida"),(97,"Kane, Hunter A.","auctor.non.feugiat@nequenon.com","2571 Ipsum Road","Seloignes","60002","Pearson","id, libero. Donec consectetuer"),(98,"Washington, Clementine Q.","risus.Nunc@euplacerat.ca","764-4651 Ante, Street","Ávila","3945HK","Shepherd","tempor bibendum. Donec felis orci, adipiscing non, luctus sit"),(99,"Padilla, Audrey K.","aliquet.diam@inhendrerit.edu","Ap #440-6841 Nec Rd.","Colwood","76678-086","Adams","vulputate"),(100,"Woodward, Hayes L.","massa@iaculislacus.ca","881-1324 Dictum Ave","Delianuova","69247","Nicholson","ut aliquam iaculis, lacus pede sagittis");
